### ISSUE TITLE
After creating the docker image, "libcuda.so.1" error come

### ISSUE THREAD

**Issue by Adnios** [CDECatapult/ml-performance-prediction#2]
Hello, author. Thank you for sharing your work. I want to get some training data using your code. In folder "Generate_train_data", Firstly, I `cp Dockerfile.conv Dockerfile`. Then I try to create a docker using command `docker build -t test:v1 .`. It is going successfully. When I try to run the docker image using command `docker run -t test:v1`, I get an error.
![image](https://user-images.githubusercontent.com/41060790/111869933-a16c0500-89bc-11eb-9025-cd5fc7be1dee.png)

**Comment by Castdeath97** [comment]
@Adnios 

I think you need to use another Dockerfile for that, I referenced this in the other issue try giving what I suggested back then a go and see what happens:

https://github.com/CDECatapult/ml-performance-prediction/issues#issuecomment-548781975

**Comment by Adnios** [comment]
> @Adnios
> 
> I think you need to use another Dockerfile for that, I referenced this in the other issue try giving what I suggested back then a go and see what happens:
> 
> https://github.com/CDECatapult/ml-performance-prediction/issues#issuecomment-548781975

thanks for your reply. I will try.
